module.exports = {
  projects: [
    '<rootDir>/apps/spotify',
    '<rootDir>/libs/shared/service',
    '<rootDir>/libs/web/lyrics/view',
    '<rootDir>/libs/web/lyrics/mini-lyrics/service',
    '<rootDir>/libs/web/lyrics/mini-lyrics/interface',
    '<rootDir>/libs/web/lyrics/model',
    '<rootDir>/libs/spotify/player/view',
    '<rootDir>/libs/spotify/homepage/view',
    '<rootDir>/libs/spotify/sidebar/view',
    '<rootDir>/libs/spotify/dashboard/view',
    '<rootDir>/libs/shared/pipes',
    '<rootDir>/libs/shared/interceptors',
    '<rootDir>/libs/web/spotify/shared/view',
    '<rootDir>/libs/web/spotify/shared/helper',
    '<rootDir>/libs/web/spotify/shared/pipe',
    '<rootDir>/libs/shared/view',
    '<rootDir>/libs/helper',
    '<rootDir>/libs/shared/helper',
  ],
};
